apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: gcr.io/mcc-2016-g09-p2/server:v1
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 8443
          name: http-server
