# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 12:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 18, 12, 56, 30, 202613)),
        ),
    ]
