# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-17 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0017_highscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='highscore',
            name='data',
            field=models.CharField(default='{}', max_length=300),
        ),
    ]
