# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-14 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0020_transaction_time_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='gamestore.Game'),
        ),
    ]
