# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-15 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0021_auto_20170214_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('AC', 'Action'), ('AD', 'Adventure'), ('AR', 'Arcade'), ('PZ', 'Puzzle'), ('RC', 'Racing'), ('SH', 'Shooting'), ('SP', 'Sports'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
