# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-17 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0018_highscore_data'),
        ('gamestore', '0022_auto_20170215_1534'),
    ]

    operations = [
    ]
