# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-01 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0023_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='data',
            field=models.CharField(default='{"score": 0,"playerItems": []}', max_length=300),
        ),
    ]
